### ISSUE TITLE
Can you provide an example of multi-label classification?

### ISSUE THREAD

**Issue by wshuyi** [ohmeow/blurr#1]
Hi! Thank you so much for this great lib! It's awesome! 

Could you please provide us an example of multi-label classification such as "toxic comments"? 

Thanks a lot!

**Comment by ohmeow** [comment]
Will add that to the do list ... but you can probably do this before we do :).  

Take a look at the "sequence classification" notebook in the docs.  For multi-classification, you just need to use a `MultiCategoryBlock` instead of the `CategoryBlock` (see [here](https://dev.fast.ai/data.block#MultiCategoryBlock) for more info).

Everything you need to prepare your data for multi-label is in the fastai docs.

**Comment by wshuyi** [comment]
Thank you so much for your reply! :)

**Comment by ohmeow** [comment]
Here ya go ... hope its helpful:

https://ohmeow.github.io/blurr/modeling-core/#Example-usage---Multi-label-classification

**Comment by wshuyi** [comment]
Great job! Thank you so much! :)
